package:
  name: pybioportal
  version: 1.0.0

source:
  url: https://github.com/Matteo-Valerio/pyBioPortal/raw/master/archive/src.tar.gz

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
  - python
  - setuptools

  run:
  - python
  - requests>=2.28.0
  - pandas>=1.5.0
  - numpy>=1.22.0

about:
  home: https://github.com/Matteo-Valerio/pyBioPortal
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A Python package to easily retrieve data from cBioPortal.
  doc_url: https://pybioportal.readthedocs.io
  description: |
    A Python package to easily retrieve data from cBioPortal.

extra:
  recipe-maintainers:
  - Matteo Valerio
