package:
  name: pybioportal
  version: "1.0.0"

source:
  git_url: "https://github.com/Matteo-Valerio/pyBioPortal.git"
  git_rev: v1.0.0
  git_depth: 1 # (Defaults to -1/not shallow)

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  run:
    - python
    - requests>=2.0.0
    - pandas>=1.0.0
    - numpy>=1.23.0

about:
  home: https://github.com/Matteo-Valerio/pyBioPortal
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A Python package to easily retrieve data from cBioPortal.
  doc_url: https://pybioportal.readthedocs.io
  description: |
    A Python package to easily retrieve data from cBioPortal.

extra:
  recipe-maintainers:
    - Matteo Valerio
