package:
  name: pybioportal
  version: 1.0.0

source:
  url: https://github.com/Matteo-Valerio/pyBioPortal/raw/master/archive/pybioportal-v1.0.0.tar.gz
  sha256: e4bbaca121aa9f9cf87595d8d607fc3e50cb45b54cb0994c663b26bc3d4d2ed9

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  run:
  - python
  - requests>=2.0.0
  - pandas>=1.0.0
  - numpy>=1.23.0

about:
  home: https://github.com/Matteo-Valerio/pyBioPortal
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A Python package to easily retrieve data from cBioPortal.
  doc_url: https://pybioportal.readthedocs.io
  description: |
    A Python package to easily retrieve data from cBioPortal.

extra:
  recipe-maintainers:
  - Matteo Valerio
